spring.application.name=transactional-outbox

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/outbox}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:outbox}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:outbox}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.locations=classpath:db/migration/{vendor}

spring.task.scheduling.pool.size=2

outbox.leader=${OUTBOX_LEADER:false}
